//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteParserR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropHistories
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int WeaponId { get; set; }
        public int CaseId { get; set; }
    
        public virtual Cases Cases { get; set; }
        public virtual Weapons Weapons { get; set; }
    }
}
