//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteParserR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Base : DbContext
    {
        public Base()
            : base("name=Base")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cases> Cases { get; set; }
        public virtual DbSet<DropHistories> DropHistories { get; set; }
        public virtual DbSet<possSkinsInCases> possSkinsInCases { get; set; }
        public virtual DbSet<Rares> Rares { get; set; }
        public virtual DbSet<SkinNs> SkinNs { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<TypeWeapImgs> TypeWeapImgs { get; set; }
        public virtual DbSet<WeapNs> WeapNs { get; set; }
        public virtual DbSet<Weapons> Weapons { get; set; }
    }
}
