//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteParserR
{
    using System;
    using System.Collections.Generic;
    
    public partial class possSkinsInCases
    {
        public int Id { get; set; }
        public Nullable<int> Caseid { get; set; }
        public Nullable<int> Weaponid { get; set; }
    
        public virtual Cases Cases { get; set; }
        public virtual Weapons Weapons { get; set; }
    }
}
