//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropHistory
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int WeaponId { get; set; }
        public int CaseId { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Weapon Weapon { get; set; }
    }
}
