//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Base : DbContext
    {
        public Base()
            : base("name=Base")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case> Case { get; set; }
        public virtual DbSet<DropHistory> DropHistory { get; set; }
        public virtual DbSet<possSkinsInCase> possSkinsInCase { get; set; }
        public virtual DbSet<Rare> Rare { get; set; }
        public virtual DbSet<SkinN> SkinN { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<WeapN> WeapN { get; set; }
        public virtual DbSet<Weapon> Weapon { get; set; }
    }
}
