//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Weapon()
        {
            this.possSkinsInCase = new HashSet<possSkinsInCase>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> SkinNameId { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> WeaponNId { get; set; }
    
        public virtual NameW NameW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<possSkinsInCase> possSkinsInCase { get; set; }
        public virtual SkinN SkinN { get; set; }
        public virtual Type Type { get; set; }
    }
}
